In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("datasets_1111_2005_kidney_disease.csv");

In [3]:
data.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [4]:
column=['sg','al','sc','hemo','pcv','wbcc','rbcc','htn','classification']

In [5]:
data=data.drop([col for col in data.columns if not col in column],axis=1)

In [6]:
data=data.dropna(axis=0)

In [7]:
data

sg   al   sc  hemo pcv  htn classification
0    1.020  1.0  1.2  15.4  44  yes            ckd
1    1.020  4.0  0.8  11.3  38   no            ckd
2    1.010  2.0  1.8   9.6  31   no            ckd
3    1.005  4.0  3.8  11.2  32  yes            ckd
4    1.010  2.0  1.4  11.6  35   no            ckd
..     ...  ...  ...   ...  ..  ...            ...
395  1.020  0.0  0.5  15.7  47   no         notckd
396  1.025  0.0  1.2  16.5  54   no         notckd
397  1.020  0.0  0.6  15.8  49   no         notckd
398  1.025  0.0  1.0  14.2  51   no         notckd
399  1.025  0.0  1.1  15.8  53   no         notckd

[287 rows x 7 columns]

In [8]:
x=data.iloc[:,0:6].values

In [9]:
y=data.iloc[:,6:].values

In [10]:
lb=LabelEncoder()
x[:,5]=lb.fit_transform(x[:,5])

In [11]:
y=lb.fit_transform(y)


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [12]:
feat_labels=['sg','al','sc','hemo','pcv','htn']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [14]:
x_train

array([[1.01, 1.0, 1.1, 15.0, '48', 0],
       [1.02, 0.0, 1.2, 16.2, '50', 0],
       [1.02, 0.0, 1.2, 15.7, '44', 0],
       ...,
       [1.015, 3.0, 3.3, 11.3, '31', 1],
       [1.01, 2.0, 3.3, 10.9, '37', 0],
       [1.025, 0.0, 0.9, 13.9, '48', 0]], dtype=object)

In [23]:

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [31]:
from joblib import dump
dump(sc,"scalar.save")

['scalar.save']

In [17]:
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [25]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor(n_estimators=10,random_state=0,n_jobs=-1)
Rf.fit(x_train,y_train)


RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=0)

In [26]:
import pickle
pickle.dump(Rf,open('decision.pkl','wb'))

In [27]:
y_pred=Rf.predict(x_test)

In [28]:
y_pred

array([0. , 1. , 0. , 0.4, 1. , 0. , 0. , 1. , 0. , 0. , 1. , 1. , 0. ,
       0. , 0. , 1. , 1. , 0.3, 0.5, 0. , 0. , 1. , 0. , 1. , 0. , 0. ,
       1. , 1. , 0. , 1. , 1. , 0. , 0. , 1. , 0. , 1. , 0. , 0.1, 0.1,
       0. , 0. , 0.5, 1. , 1. , 1. , 0. , 1. , 1. , 0. , 1. , 0. , 0.5,
       1. , 1. , 0. , 0.2, 1. , 0. ])

In [29]:
y_test

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

In [30]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.870924495924496